- name: Run roles on all Linux inventory nodes
  hosts: linux
  become: yes
  gather_facts: yes
  vars:
    ansible_managed: "Managed by Ansible"
    ansible_ssh_private_key_file: "~/.ssh/id_rsa"
  roles:
    - datadisk-n01569982
    - profile-n01569982
    - user-n01569982
    - webserver-n01569982